name: basic
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  avatar_glow: ^2.0.2
  convex_bottom_bar: ^3.1.0+1
  cupertino_icons: ^1.0.2
  dropdown_search: ^5.0.5
  faker: ^2.0.0
  flutter:
    sdk: flutter
  get: ^4.6.5
  get_storage: ^2.0.3
  http: ^0.13.5
  intl: ^0.17.0
  introduction_screen: ^3.1.1
  lottie: ^2.0.0

dev_dependencies:
  flutter_launcher_icons: "^0.11.0"
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
